events {}

http {
    server {
        listen 80;                    # ← Внутри контейнера 80
        
        location / {
            proxy_pass http://app:5000;   # ← app сервис :5000 порт
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }
}
